function [fitresult, gof, xData, yData] = createFit(x, data)
%CREATEFIT(x,data)
% Author: Hunter Hinceman
% Date: June 4, 2019
%
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : z
%      Y Output: zh
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 04-Jun-2019 11:39:21

[xData, yData] = prepareCurveData(x, data );

% Set up fittype and options.
% ft = fittype( 'a.*(X1.^4) + b.*(X.^2) + c.*X + d;', 'independent', 'X', 'dependent', 'y' );
% opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
% opts.Display = 'Off';
% opts.StartPoint = [5.1638e-10    9.7913e-04    9.7913e-04   -3.3293e-04    -7.1564];

% attempt LINEAR model
ft = fittype( {'(x).^4', '(x).^2', 'x', '(x).^0'}, 'coefficients', {'a', 'b', 'c', 'd'});
opts = fitoptions( 'Method', 'LinearLeastSquares' );
% opts.Display = 'Off';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% y = fitresult(x);
% residual = data - y ;
% ResidualFig = figure, plot (x, residual);

